// Realistic Vietnamese retail mock data

export interface Category {
  id: string;
  name: string;
  description: string;
  active: boolean;
  productCount: number;
}

export interface ProductVariant {
  id: string;
  code: string;
  name: string;
  sellUnit: string;
  importUnit: string;
  piecesPerImportUnit: number;
  sellPrice: number;
  costPrice: number;
  stock: number;
  minStock: number;
  expiryDays: number;
  isDefault: boolean;
  expiryDate?: string;
  /** Optional override — falls back to product.image when empty */
  image?: string;
}

export interface Product {
  id: string;
  code: string;
  name: string;
  categoryId: string;
  categoryName: string;
  /** Product-level image (data URL or remote URL). May be empty. */
  image: string;
  /** Optional gallery (additional product-level images) */
  images?: string[];
  active: boolean;
  variants: ProductVariant[];
  type: 'single' | 'multi';
}

export interface ComboItem {
  productId: string;
  variantId: string;
  productName: string;
  variantName: string;
  quantity: number;
  stock: number;
}

export interface Combo {
  id: string;
  code: string;
  name: string;
  image: string;
  price: number;
  active: boolean;
  components: ComboItem[];
  derivedStock: number;
}

export interface Customer {
  id: string;
  code: string;
  name: string;
  phone: string;
  email?: string;
  group: 'retail' | 'wholesale' | 'vip';
  active: boolean;
  totalPurchases: number;
  lastPurchaseDate?: string;
  orderCount: number;
}

export interface Supplier {
  id: string;
  code: string;
  name: string;
  phone: string;
  address: string;
  taxCode: string;
  email: string;
  note?: string;
  active: boolean;
}

export interface InvoiceLine {
  name: string;
  code: string;
  qty: number;
  price: number;
  /** true if this is a free reward line generated by a promotion */
  reward?: boolean;
  rewardSource?: string;
}

export interface InvoiceBreakdown {
  subtotal: number;
  manualDiscount: number;
  promoDiscount: number;
  promoName?: string;
  shippingFee: number;
  shippingDiscount: number;
  shippingPayable: number;
  vatPercent: number;
  vatBase: number;
  vatAmount: number;
  total: number;
  freeItems?: { productName: string; quantity: number }[];
}

export interface Invoice {
  id: string;
  number: string;
  date: string;
  customerId: string;
  customerName: string;
  total: number;
  paymentType: 'cash' | 'transfer' | 'momo' | 'zalopay';
  status: 'active' | 'cancelled';
  createdBy: string;
  itemCount: number;
  /** Snapshot of POS computed breakdown — source of truth for invoice detail */
  breakdown?: InvoiceBreakdown;
  /** Snapshot of cart lines including reward/gift lines */
  lines?: InvoiceLine[];
  note?: string;
}

export interface PendingOrder {
  id: string;
  orderNumber: string;
  customerId: string;
  customerName: string;
  paymentMethod: 'transfer' | 'momo' | 'zalopay';
  total: number;
  createdAt: string;
  expiresAt: string;
  status: 'pending' | 'confirmed' | 'cancelled' | 'expired';
  itemCount: number;
  items?: { name: string; qty: number; price: number }[];
}

export interface GoodsReceipt {
  id: string;
  number: string;
  date: string;
  supplierId: string;
  supplierName: string;
  itemCount: number;
  totalCost: number;
  shippingFee: number;
  vat: number;
  note?: string;
  canDelete: boolean;
}

export interface GoodsReceiptLine {
  id: string;
  productName: string;
  variantName: string;
  variantCode: string;
  quantity: number;
  /** Đơn giá gốc theo importUnit, trước chiết khấu (nguồn từ BE) */
  unitCost: number;
  /** % chiết khấu áp dụng trên unitCost (nguồn từ BE) */
  discount: number;
  importUnit: string;
  piecesPerUnit: number;
  expiryDate?: string;
  /** BE-allocated breakdown (source of truth for cost columns) */
  lineSubtotal?: number;       // quantity * unitCost
  afterDiscount?: number;      // lineSubtotal * (1 - discount/100)
  shippingAlloc?: number;      // tỉ lệ phân bổ phí vận chuyển
  vatAlloc?: number;           // tỉ lệ phân bổ VAT
  finalUnitCost?: number;      // giá vốn cuối / 1 importUnit (đã gồm CK + ship + VAT)
}

export interface StockAdjustment {
  id: string;
  code: string;
  createdDate: string;
  reason: string;
  note: string;
  itemCount: number;
  status: 'draft' | 'confirmed';
  createdBy?: string;
}

export interface StockAdjustmentLine {
  id: string;
  variantCode: string;
  productName: string;
  variantName: string;
  systemQty: number;
  actualQty: number;
  difference: number;
  note: string;
}

export interface Promotion {
  id: string;
  name: string;
  description: string;
  type: 'percent' | 'fixed' | 'buy-x-get-y' | 'gift' | 'free-shipping';
  active: boolean;
  startDate: string;
  endDate: string;
  minOrderValue: number;
  maxDiscount: number;
  discountValue: number;
  scope: 'all' | 'categories' | 'products';
  scopeIds: string[];
}

export interface UserAccount {
  id: string;
  username: string;
  fullName: string;
  role: 'admin' | 'staff';
  active: boolean;
  totpEnabled: boolean;
  lastLogin?: string;
  createdAt: string;
}

export interface InventoryReportRow {
  variantCode: string;
  productName: string;
  variantName: string;
  unit: string;
  openingStock: number;
  received: number;
  sold: number;
  adjusted: number;
  closingStock: number;
  closingValue: number;
}

export interface RevenueRow {
  period: string;
  revenue: number;
  invoiceCount: number;
  itemsSold: number;
}

export interface ProfitRow {
  period: string;
  revenue: number;
  cost: number;
  profit: number;
  margin: number;
  invoiceCount: number;
}

// === MOCK DATA ===

export const categories: Category[] = [
  { id: '1', name: 'Thực phẩm khô', description: 'Mì, bún, phở, gia vị', active: true, productCount: 24 },
  { id: '2', name: 'Đồ uống', description: 'Nước ngọt, trà, cà phê', active: true, productCount: 18 },
  { id: '3', name: 'Bánh kẹo', description: 'Bánh quy, kẹo, snack', active: true, productCount: 32 },
  { id: '4', name: 'Sữa & Chế phẩm', description: 'Sữa tươi, sữa chua, phô mai', active: true, productCount: 15 },
  { id: '5', name: 'Đồ dùng gia đình', description: 'Giấy, xà phòng, chất tẩy', active: true, productCount: 20 },
  { id: '6', name: 'Rau củ quả', description: 'Rau xanh, trái cây tươi', active: false, productCount: 0 },
];

export const products: Product[] = [
  {
    id: '1', code: 'SP001', name: 'Mì Hảo Hảo', categoryId: '1', categoryName: 'Thực phẩm khô',
    image: '', active: true, type: 'multi',
    variants: [
      { id: 'v1', code: 'SP001-01', name: 'Tôm chua cay', sellUnit: 'Gói', importUnit: 'Thùng', piecesPerImportUnit: 30, sellPrice: 5000, costPrice: 3500, stock: 245, minStock: 50, expiryDays: 180, isDefault: true },
      { id: 'v2', code: 'SP001-02', name: 'Lẩu Thái', sellUnit: 'Gói', importUnit: 'Thùng', piecesPerImportUnit: 30, sellPrice: 5500, costPrice: 3800, stock: 12, minStock: 50, expiryDays: 180, isDefault: false },
      { id: 'v3', code: 'SP001-03', name: 'Sa tế', sellUnit: 'Gói', importUnit: 'Thùng', piecesPerImportUnit: 30, sellPrice: 5000, costPrice: 3500, stock: 0, minStock: 50, expiryDays: 180, isDefault: false },
    ],
  },
  {
    id: '2', code: 'SP002', name: 'Coca-Cola', categoryId: '2', categoryName: 'Đồ uống',
    image: '', active: true, type: 'multi',
    variants: [
      { id: 'v4', code: 'SP002-01', name: 'Lon 330ml', sellUnit: 'Lon', importUnit: 'Thùng', piecesPerImportUnit: 24, sellPrice: 10000, costPrice: 7200, stock: 180, minStock: 30, expiryDays: 365, isDefault: true },
      { id: 'v5', code: 'SP002-02', name: 'Chai 1.5L', sellUnit: 'Chai', importUnit: 'Thùng', piecesPerImportUnit: 12, sellPrice: 18000, costPrice: 13500, stock: 45, minStock: 20, expiryDays: 365, isDefault: false },
    ],
  },
  {
    id: '3', code: 'SP003', name: 'Sữa Vinamilk 100%', categoryId: '4', categoryName: 'Sữa & Chế phẩm',
    image: '', active: true, type: 'multi',
    variants: [
      { id: 'v6', code: 'SP003-01', name: 'Hộp 180ml', sellUnit: 'Hộp', importUnit: 'Lốc', piecesPerImportUnit: 4, sellPrice: 8000, costPrice: 6000, stock: 96, minStock: 24, expiryDays: 90, isDefault: true, expiryDate: '2025-05-10' },
      { id: 'v7', code: 'SP003-02', name: 'Hộp 1L', sellUnit: 'Hộp', importUnit: 'Thùng', piecesPerImportUnit: 12, sellPrice: 32000, costPrice: 25000, stock: 8, minStock: 10, expiryDays: 90, isDefault: false, expiryDate: '2025-04-20' },
    ],
  },
  {
    id: '4', code: 'SP004', name: 'Bánh Oreo', categoryId: '3', categoryName: 'Bánh kẹo',
    image: '', active: true, type: 'multi',
    variants: [
      { id: 'v8', code: 'SP004-01', name: 'Gói 133g', sellUnit: 'Gói', importUnit: 'Thùng', piecesPerImportUnit: 24, sellPrice: 22000, costPrice: 16000, stock: 67, minStock: 20, expiryDays: 270, isDefault: true },
      { id: 'v9', code: 'SP004-02', name: 'Hộp 266g', sellUnit: 'Hộp', importUnit: 'Thùng', piecesPerImportUnit: 12, sellPrice: 42000, costPrice: 32000, stock: 23, minStock: 10, expiryDays: 270, isDefault: false },
    ],
  },
  {
    id: '5', code: 'SP005', name: 'Nước mắm Nam Ngư', categoryId: '1', categoryName: 'Thực phẩm khô',
    image: '', active: true, type: 'single',
    variants: [
      { id: 'v10', code: 'SP005-01', name: 'Chai 500ml', sellUnit: 'Chai', importUnit: 'Thùng', piecesPerImportUnit: 12, sellPrice: 28000, costPrice: 20000, stock: 54, minStock: 15, expiryDays: 540, isDefault: true },
    ],
  },
  {
    id: '6', code: 'SP006', name: 'Giấy vệ sinh Pulppy', categoryId: '5', categoryName: 'Đồ dùng gia đình',
    image: '', active: true, type: 'single',
    variants: [
      { id: 'v11', code: 'SP006-01', name: 'Gói 6 cuộn', sellUnit: 'Gói', importUnit: 'Bịch', piecesPerImportUnit: 10, sellPrice: 55000, costPrice: 40000, stock: 3, minStock: 10, expiryDays: 0, isDefault: true },
    ],
  },
  {
    id: '7', code: 'SP007', name: 'Trà Lipton', categoryId: '2', categoryName: 'Đồ uống',
    image: '', active: true, type: 'multi',
    variants: [
      { id: 'v12', code: 'SP007-01', name: 'Hộp 25 gói', sellUnit: 'Hộp', importUnit: 'Thùng', piecesPerImportUnit: 24, sellPrice: 45000, costPrice: 32000, stock: 38, minStock: 10, expiryDays: 365, isDefault: true },
      { id: 'v13', code: 'SP007-02', name: 'Chai 455ml', sellUnit: 'Chai', importUnit: 'Thùng', piecesPerImportUnit: 24, sellPrice: 10000, costPrice: 7000, stock: 0, minStock: 20, expiryDays: 180, isDefault: false },
    ],
  },
  {
    id: '8', code: 'SP008', name: 'Kem đánh răng P/S', categoryId: '5', categoryName: 'Đồ dùng gia đình',
    image: '', active: true, type: 'single',
    variants: [
      { id: 'v14', code: 'SP008-01', name: 'Tuýp 180g', sellUnit: 'Tuýp', importUnit: 'Hộp', piecesPerImportUnit: 36, sellPrice: 35000, costPrice: 25000, stock: 42, minStock: 12, expiryDays: 720, isDefault: true },
    ],
  },
];

export const combos: Combo[] = [
  {
    id: 'c1', code: 'CB001', name: 'Combo Gia Đình', image: '', price: 120000, active: true, derivedStock: 3,
    components: [
      { productId: '1', variantId: 'v1', productName: 'Mì Hảo Hảo', variantName: 'Tôm chua cay', quantity: 5, stock: 245 },
      { productId: '2', variantId: 'v4', productName: 'Coca-Cola', variantName: 'Lon 330ml', quantity: 6, stock: 180 },
      { productId: '3', variantId: 'v6', productName: 'Sữa Vinamilk', variantName: 'Hộp 180ml', quantity: 4, stock: 96 },
    ],
  },
  {
    id: 'c2', code: 'CB002', name: 'Combo Tiết Kiệm', image: '', price: 65000, active: true, derivedStock: 12,
    components: [
      { productId: '1', variantId: 'v1', productName: 'Mì Hảo Hảo', variantName: 'Tôm chua cay', quantity: 10, stock: 245 },
      { productId: '7', variantId: 'v12', productName: 'Trà Lipton', variantName: 'Hộp 25 gói', quantity: 1, stock: 38 },
    ],
  },
  {
    id: 'c3', code: 'CB003', name: 'Combo Sinh Nhật', image: '', price: 180000, active: false, derivedStock: 0,
    components: [
      { productId: '4', variantId: 'v9', productName: 'Bánh Oreo', variantName: 'Hộp 266g', quantity: 2, stock: 23 },
      { productId: '2', variantId: 'v5', productName: 'Coca-Cola', variantName: 'Chai 1.5L', quantity: 2, stock: 45 },
    ],
  },
];

export const customers: Customer[] = [
  { id: '1', code: 'KH001', name: 'Nguyễn Văn An', phone: '0901234567', email: 'an.nguyen@gmail.com', group: 'vip', active: true, totalPurchases: 45200000, lastPurchaseDate: '2025-04-15', orderCount: 87 },
  { id: '2', code: 'KH002', name: 'Trần Thị Bình', phone: '0912345678', email: 'binh.tran@gmail.com', group: 'retail', active: true, totalPurchases: 8500000, lastPurchaseDate: '2025-04-15', orderCount: 23 },
  { id: '3', code: 'KH003', name: 'Lê Hoàng Cường', phone: '0923456789', email: 'cuong.le@company.vn', group: 'wholesale', active: true, totalPurchases: 125000000, lastPurchaseDate: '2025-04-14', orderCount: 156 },
  { id: '4', code: 'KH004', name: 'Phạm Minh Đức', phone: '0934567890', group: 'retail', active: false, totalPurchases: 2100000, lastPurchaseDate: '2025-02-10', orderCount: 5 },
  { id: '5', code: 'KH005', name: 'Võ Thị Em', phone: '0945678901', email: 'em.vo@gmail.com', group: 'retail', active: true, totalPurchases: 15300000, lastPurchaseDate: '2025-04-13', orderCount: 42 },
  { id: '6', code: 'KH006', name: 'Huỳnh Văn Phú', phone: '0956789012', group: 'wholesale', active: true, totalPurchases: 78000000, lastPurchaseDate: '2025-04-12', orderCount: 98 },
  { id: '7', code: 'KH007', name: 'Đặng Thị Quỳnh', phone: '0967890123', group: 'retail', active: true, totalPurchases: 4200000, lastPurchaseDate: '2025-04-10', orderCount: 12 },
];

export const suppliers: Supplier[] = [
  { id: '1', code: 'NCC001', name: 'Công ty TNHH Thực Phẩm Á Châu', phone: '02812345678', address: '123 Nguyễn Văn Linh, Q7, TP.HCM', taxCode: '0301234567', email: 'contact@acfood.vn', active: true },
  { id: '2', code: 'NCC002', name: 'Đại lý Phát Đạt', phone: '02887654321', address: '456 Lê Văn Việt, Q9, TP.HCM', taxCode: '0307654321', email: 'phatdat@gmail.com', active: true },
  { id: '3', code: 'NCC003', name: 'Công ty CP Vinamilk', phone: '02838155555', address: '10 Tân Trào, Q7, TP.HCM', taxCode: '0300588569', email: 'vinamilk@vinamilk.com.vn', active: true },
  { id: '4', code: 'NCC004', name: 'Công ty TNHH Unilever VN', phone: '02839325511', address: '156 Nguyễn Lương Bằng, Q7, TP.HCM', taxCode: '0300589777', email: 'unilever@unilever.vn', note: 'Liên hệ anh Minh - 0901222333', active: true },
  { id: '5', code: 'NCC005', name: 'Đại lý Hoàng Long', phone: '02866778899', address: '789 Quốc lộ 1A, Q12, TP.HCM', taxCode: '0312345678', email: 'hoanglong@gmail.com', active: false },
];

export const invoices: Invoice[] = [
  { id: '1', number: 'HD-20250415-001', date: '2025-04-15T08:30:00+07:00', customerId: '1', customerName: 'Nguyễn Văn An', total: 285000, paymentType: 'cash', status: 'active', createdBy: 'admin', itemCount: 5 },
  { id: '2', number: 'HD-20250415-002', date: '2025-04-15T09:15:00+07:00', customerId: '2', customerName: 'Trần Thị Bình', total: 152000, paymentType: 'transfer', status: 'active', createdBy: 'admin', itemCount: 3 },
  { id: '3', number: 'HD-20250415-003', date: '2025-04-15T11:45:00+07:00', customerId: '', customerName: 'Khách lẻ', total: 73000, paymentType: 'cash', status: 'active', createdBy: 'nhanvien1', itemCount: 4 },
  { id: '4', number: 'HD-20250414-001', date: '2025-04-14T14:20:00+07:00', customerId: '', customerName: 'Khách lẻ', total: 45000, paymentType: 'cash', status: 'active', createdBy: 'nhanvien1', itemCount: 2 },
  { id: '5', number: 'HD-20250414-002', date: '2025-04-14T16:45:00+07:00', customerId: '3', customerName: 'Lê Hoàng Cường', total: 1250000, paymentType: 'transfer', status: 'cancelled', createdBy: 'admin', itemCount: 8 },
  { id: '6', number: 'HD-20250413-001', date: '2025-04-13T10:00:00+07:00', customerId: '5', customerName: 'Võ Thị Em', total: 98000, paymentType: 'momo', status: 'active', createdBy: 'admin', itemCount: 4 },
  { id: '7', number: 'HD-20250413-002', date: '2025-04-13T15:30:00+07:00', customerId: '6', customerName: 'Huỳnh Văn Phú', total: 2450000, paymentType: 'cash', status: 'active', createdBy: 'admin', itemCount: 12 },
  { id: '8', number: 'HD-20250412-001', date: '2025-04-12T09:00:00+07:00', customerId: '1', customerName: 'Nguyễn Văn An', total: 567000, paymentType: 'zalopay', status: 'active', createdBy: 'nhanvien1', itemCount: 6 },
];

export const pendingOrders: PendingOrder[] = [
  { id: '1', orderNumber: 'DH-20250415-001', customerId: '2', customerName: 'Trần Thị Bình', paymentMethod: 'transfer', total: 320000, createdAt: '2025-04-15T10:30:00+07:00', expiresAt: '2025-04-15T22:30:00+07:00', status: 'pending', itemCount: 4, items: [{ name: 'Mì Hảo Hảo - Tôm chua cay', qty: 10, price: 5000 }, { name: 'Coca-Cola - Lon 330ml', qty: 6, price: 10000 }, { name: 'Sữa Vinamilk - Hộp 180ml', qty: 10, price: 8000 }] },
  { id: '2', orderNumber: 'DH-20250415-002', customerId: '5', customerName: 'Võ Thị Em', paymentMethod: 'momo', total: 185000, createdAt: '2025-04-15T11:00:00+07:00', expiresAt: '2025-04-15T23:00:00+07:00', status: 'pending', itemCount: 2, items: [{ name: 'Bánh Oreo - Gói 133g', qty: 3, price: 22000 }, { name: 'Trà Lipton - Hộp 25 gói', qty: 2, price: 45000 }] },
  { id: '3', orderNumber: 'DH-20250414-001', customerId: '1', customerName: 'Nguyễn Văn An', paymentMethod: 'zalopay', total: 450000, createdAt: '2025-04-14T09:00:00+07:00', expiresAt: '2025-04-14T21:00:00+07:00', status: 'confirmed', itemCount: 6 },
  { id: '4', orderNumber: 'DH-20250413-001', customerId: '3', customerName: 'Lê Hoàng Cường', paymentMethod: 'transfer', total: 890000, createdAt: '2025-04-13T15:00:00+07:00', expiresAt: '2025-04-14T03:00:00+07:00', status: 'expired', itemCount: 5 },
  { id: '5', orderNumber: 'DH-20250412-001', customerId: '7', customerName: 'Đặng Thị Quỳnh', paymentMethod: 'transfer', total: 156000, createdAt: '2025-04-12T14:00:00+07:00', expiresAt: '2025-04-13T02:00:00+07:00', status: 'cancelled', itemCount: 3 },
];

export const goodsReceipts: GoodsReceipt[] = [
  { id: '1', number: 'PN-20250415-001', date: '2025-04-15', supplierId: '1', supplierName: 'Công ty TNHH Thực Phẩm Á Châu', itemCount: 5, totalCost: 3500000, shippingFee: 50000, vat: 350000, note: 'Nhập hàng tuần', canDelete: true },
  { id: '2', number: 'PN-20250412-001', date: '2025-04-12', supplierId: '3', supplierName: 'Công ty CP Vinamilk', itemCount: 3, totalCost: 8200000, shippingFee: 0, vat: 820000, canDelete: false },
  { id: '3', number: 'PN-20250410-001', date: '2025-04-10', supplierId: '2', supplierName: 'Đại lý Phát Đạt', itemCount: 8, totalCost: 12500000, shippingFee: 100000, vat: 1250000, canDelete: false },
  { id: '4', number: 'PN-20250408-001', date: '2025-04-08', supplierId: '4', supplierName: 'Công ty TNHH Unilever VN', itemCount: 4, totalCost: 5600000, shippingFee: 0, vat: 560000, canDelete: false },
  { id: '5', number: 'PN-20250405-001', date: '2025-04-05', supplierId: '1', supplierName: 'Công ty TNHH Thực Phẩm Á Châu', itemCount: 6, totalCost: 4200000, shippingFee: 50000, vat: 420000, canDelete: false },
];

export const mockReceiptLines: GoodsReceiptLine[] = [
  { id: 'rl1', productName: 'Mì Hảo Hảo', variantName: 'Tôm chua cay', variantCode: 'SP001-01', quantity: 10, unitCost: 105000, discount: 0, importUnit: 'Thùng', piecesPerUnit: 30, expiryDate: '2025-10-15' },
  { id: 'rl2', productName: 'Mì Hảo Hảo', variantName: 'Lẩu Thái', variantCode: 'SP001-02', quantity: 5, unitCost: 114000, discount: 2, importUnit: 'Thùng', piecesPerUnit: 30, expiryDate: '2025-10-15' },
  { id: 'rl3', productName: 'Coca-Cola', variantName: 'Lon 330ml', variantCode: 'SP002-01', quantity: 8, unitCost: 172800, discount: 0, importUnit: 'Thùng', piecesPerUnit: 24, expiryDate: '2026-04-15' },
];

export const stockAdjustments: StockAdjustment[] = [
  { id: '1', code: 'DC-20250415-001', createdDate: '2025-04-15', reason: 'Kiểm kho định kỳ', note: 'Kiểm kho tháng 4/2025', itemCount: 12, status: 'draft', createdBy: 'admin' },
  { id: '2', code: 'DC-20250410-001', createdDate: '2025-04-10', reason: 'Hàng hỏng', note: 'Phát hiện hàng hỏng kho 2', itemCount: 3, status: 'confirmed', createdBy: 'admin' },
  { id: '3', code: 'DC-20250405-001', createdDate: '2025-04-05', reason: 'Kiểm kho định kỳ', note: 'Kiểm kho đầu tháng 4', itemCount: 25, status: 'confirmed', createdBy: 'nhanvien1' },
];

export const mockAdjustmentLines: StockAdjustmentLine[] = [
  { id: 'al1', variantCode: 'SP001-01', productName: 'Mì Hảo Hảo', variantName: 'Tôm chua cay', systemQty: 250, actualQty: 245, difference: -5, note: 'Hàng hỏng bao bì' },
  { id: 'al2', variantCode: 'SP002-01', productName: 'Coca-Cola', variantName: 'Lon 330ml', systemQty: 178, actualQty: 180, difference: 2, note: 'Đếm thiếu lần trước' },
  { id: 'al3', variantCode: 'SP003-02', productName: 'Sữa Vinamilk', variantName: 'Hộp 1L', systemQty: 10, actualQty: 8, difference: -2, note: 'Hàng hết hạn loại bỏ' },
  { id: 'al4', variantCode: 'SP006-01', productName: 'Giấy vệ sinh Pulppy', variantName: 'Gói 6 cuộn', systemQty: 5, actualQty: 3, difference: -2, note: 'Hư hỏng do nước' },
];

export const promotions: Promotion[] = [
  { id: '1', name: 'Giảm 10% toàn bộ', description: 'Khuyến mãi cuối tuần', type: 'percent', active: true, startDate: '2026-01-01', endDate: '2026-12-31', minOrderValue: 100000, maxDiscount: 50000, discountValue: 10, scope: 'all', scopeIds: [] },
  {
    id: '2', name: 'Mua 5 tặng 1 Mì Hảo Hảo', description: 'Áp dụng cho mì gói', type: 'buy-x-get-y', active: true,
    startDate: '2026-01-01', endDate: '2026-12-31',
    minOrderValue: 0, maxDiscount: 0, discountValue: 0, scope: 'products', scopeIds: ['1'],
    // type-specific fields used by the promotions engine
    buyItems: [{ productId: '1', productName: 'Mì Hảo Hảo', quantity: 5 }],
    getItems: [{ productId: '1', productName: 'Mì Hảo Hảo', quantity: 1 }],
    mode: 'same', repeatable: true,
  } as any,
  { id: '3', name: 'Giảm 20.000đ cho đơn từ 200K', description: 'Áp dụng mọi sản phẩm', type: 'fixed', active: true, startDate: '2026-01-01', endDate: '2026-12-31', minOrderValue: 200000, maxDiscount: 20000, discountValue: 20000, scope: 'all', scopeIds: [] },
  { id: '4', name: 'Miễn phí vận chuyển', description: 'Đơn từ 300K', type: 'free-shipping', active: true, startDate: '2026-01-01', endDate: '2026-12-31', minOrderValue: 300000, maxDiscount: 0, discountValue: 0, scope: 'all', scopeIds: [] },
];

export const userAccounts: UserAccount[] = [
  { id: '1', username: 'admin', fullName: 'Nguyễn Nhà Đan', role: 'admin', active: true, totpEnabled: true, lastLogin: '2025-04-15T08:00:00+07:00', createdAt: '2024-01-01' },
  { id: '2', username: 'nhanvien1', fullName: 'Trần Thị Lan', role: 'staff', active: true, totpEnabled: true, lastLogin: '2025-04-15T07:30:00+07:00', createdAt: '2024-06-15' },
  { id: '3', username: 'nhanvien2', fullName: 'Phạm Văn Hùng', role: 'staff', active: true, totpEnabled: false, lastLogin: '2025-04-14T16:00:00+07:00', createdAt: '2024-09-01' },
  { id: '4', username: 'nhanvien3', fullName: 'Lê Thị Mai', role: 'staff', active: false, totpEnabled: false, lastLogin: '2025-03-20T10:00:00+07:00', createdAt: '2024-11-01' },
];

export const inventoryReport: InventoryReportRow[] = [
  { variantCode: 'SP001-01', productName: 'Mì Hảo Hảo', variantName: 'Tôm chua cay', unit: 'Gói', openingStock: 200, received: 300, sold: 255, adjusted: 0, closingStock: 245, closingValue: 857500 },
  { variantCode: 'SP001-02', productName: 'Mì Hảo Hảo', variantName: 'Lẩu Thái', unit: 'Gói', openingStock: 80, received: 150, sold: 218, adjusted: 0, closingStock: 12, closingValue: 45600 },
  { variantCode: 'SP001-03', productName: 'Mì Hảo Hảo', variantName: 'Sa tế', unit: 'Gói', openingStock: 50, received: 0, sold: 50, adjusted: 0, closingStock: 0, closingValue: 0 },
  { variantCode: 'SP002-01', productName: 'Coca-Cola', variantName: 'Lon 330ml', unit: 'Lon', openingStock: 150, received: 192, sold: 162, adjusted: 0, closingStock: 180, closingValue: 1296000 },
  { variantCode: 'SP002-02', productName: 'Coca-Cola', variantName: 'Chai 1.5L', unit: 'Chai', openingStock: 30, received: 48, sold: 33, adjusted: 0, closingStock: 45, closingValue: 607500 },
  { variantCode: 'SP003-01', productName: 'Sữa Vinamilk', variantName: 'Hộp 180ml', unit: 'Hộp', openingStock: 80, received: 120, sold: 104, adjusted: 0, closingStock: 96, closingValue: 576000 },
  { variantCode: 'SP003-02', productName: 'Sữa Vinamilk', variantName: 'Hộp 1L', unit: 'Hộp', openingStock: 15, received: 24, sold: 29, adjusted: -2, closingStock: 8, closingValue: 200000 },
  { variantCode: 'SP004-01', productName: 'Bánh Oreo', variantName: 'Gói 133g', unit: 'Gói', openingStock: 50, received: 72, sold: 55, adjusted: 0, closingStock: 67, closingValue: 1072000 },
  { variantCode: 'SP006-01', productName: 'Giấy vệ sinh Pulppy', variantName: 'Gói 6 cuộn', unit: 'Gói', openingStock: 15, received: 0, sold: 10, adjusted: -2, closingStock: 3, closingValue: 120000 },
];

export const revenueData: RevenueRow[] = [
  { period: '15/04/2025', revenue: 2850000, invoiceCount: 8, itemsSold: 45 },
  { period: '14/04/2025', revenue: 3150000, invoiceCount: 12, itemsSold: 67 },
  { period: '13/04/2025', revenue: 2548000, invoiceCount: 9, itemsSold: 38 },
  { period: '12/04/2025', revenue: 4200000, invoiceCount: 15, itemsSold: 89 },
  { period: '11/04/2025', revenue: 1900000, invoiceCount: 7, itemsSold: 28 },
  { period: '10/04/2025', revenue: 3650000, invoiceCount: 11, itemsSold: 52 },
  { period: '09/04/2025', revenue: 2100000, invoiceCount: 8, itemsSold: 35 },
];

export const profitData: ProfitRow[] = [
  { period: 'Tuần 15 (07-13/04)', revenue: 14398000, cost: 10439000, profit: 3959000, margin: 0.275, invoiceCount: 47 },
  { period: 'Tuần 16 (14-15/04)', revenue: 6000000, cost: 4350000, profit: 1650000, margin: 0.275, invoiceCount: 20 },
];

export const revenueByProduct = [
  { name: 'Mì Hảo Hảo - Tôm chua cay', revenue: 4500000, qty: 900 },
  { name: 'Coca-Cola - Lon 330ml', revenue: 3200000, qty: 320 },
  { name: 'Sữa Vinamilk - Hộp 180ml', revenue: 2400000, qty: 300 },
  { name: 'Giấy vệ sinh Pulppy', revenue: 1650000, qty: 30 },
  { name: 'Bánh Oreo - Gói 133g', revenue: 1540000, qty: 70 },
];

export const revenueByCategory = [
  { name: 'Thực phẩm khô', revenue: 6200000 },
  { name: 'Đồ uống', revenue: 4800000 },
  { name: 'Sữa & Chế phẩm', revenue: 3100000 },
  { name: 'Đồ dùng gia đình', revenue: 2450000 },
  { name: 'Bánh kẹo', revenue: 1950000 },
];

// Dashboard stats
export const dashboardStats = {
  revenueThisWeek: 12500000,
  revenueThisMonth: 48200000,
  profitThisWeek: 3750000,
  profitThisMonth: 14460000,
  pendingOrdersCount: 2,
  invoiceCountToday: 8,
  lowStockVariants: [
    { productName: 'Mì Hảo Hảo', variantName: 'Lẩu Thái', stock: 12, minStock: 50 },
    { productName: 'Giấy vệ sinh Pulppy', variantName: 'Gói 6 cuộn', stock: 3, minStock: 10 },
    { productName: 'Sữa Vinamilk', variantName: 'Hộp 1L', stock: 8, minStock: 10 },
  ],
  nearExpiryLots: [
    { productName: 'Sữa Vinamilk', variantName: 'Hộp 1L', expiryDate: '2025-04-20', stock: 8 },
  ],
  expiredLots: [
    { productName: 'Sữa chua Vinamilk', variantName: 'Lốc 4 hộp', expiryDate: '2025-04-10', stock: 5 },
  ],
  outOfStockVariants: [
    { productName: 'Mì Hảo Hảo', variantName: 'Sa tế', stock: 0 },
    { productName: 'Trà Lipton', variantName: 'Chai 455ml', stock: 0 },
  ],
};
